import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import type { Metadata } from 'next';
import Provider from '@/providers';
import { Inter } from 'next/font/google';
import { ViewTransitions } from 'next-view-transitions';
import socket from '@/libs/socket';

export const metadata: Metadata = {
    title: 'Messenger',
    description: 'Generated by create next app',
    icons: '/images/logo.png',
};

socket.on('connection', () => {
    console.log('I am connected');
});

const font = Inter({ subsets: ['latin'] });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ViewTransitions>
            <html lang='en'>
                <body className={font.className}>
                    <Provider>
                        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
                    </Provider>
                </body>
            </html>
        </ViewTransitions>
    );
}
