import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import type { Metadata } from 'next';
import Header from './(main)/_layout/Header';
// import StoreProvider from './StoreProvider';
// import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import StoreProvider from './StoreProvider';

export const metadata: Metadata = {
    title: 'Messenger',
    description: 'Generated by create next app',
    icons: '/images/logo.png',
};

// const queryClient = new QueryClient({
//     defaultOptions: {
//         queries: {
//             staleTime: Infinity,
//             refetchIntervalInBackground: false,
//             refetchOnWindowFocus: false,
//         },
//     },
// });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body>
                <StoreProvider>
                    <AppRouterCacheProvider>
                        <Header>{children}</Header>
                    </AppRouterCacheProvider>
                </StoreProvider>
            </body>
        </html>
    );
}
